import type { Metadata } from "next";
import { Container, CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "@/config/theme";
import RTLProvider from "@/components/common/RTLProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <CssBaseline />
        <ThemeProvider theme={theme}>
          <RTLProvider>
            <Container>{children}</Container>
          </RTLProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
